config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: 'home#index'

  resources :users, only: [:new, :create, :show] do
    collection do
      get :show_verify
    end

    member do
      post :verify
      post :resend
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  name            :string           not null
#  password_digest :string           not null
#  country_code    :string           default("1"), not null
#  phone_number    :string           not null
#  authy_id        :string
#  verified        :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_authy_id  (authy_id) UNIQUE
#  index_users_on_email     (email) UNIQUE
#

class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true,
                    format: {with: /\A.+@.+$\Z/},
                    uniqueness: true
  validates :name, presence: true
  validates :country_code, presence: true
  validates :phone_number, presence: true

  def verify!
    update(verified: true)
  end

  def formatted_phone_number
    country_code + phone_number
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def set_user_session(user)
    session[:user_id] = user.id
  end

  def unset_user_session
    session[:user_id] = nil
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def signed_in?
    current_user.present?
  end
  helper_method :signed_in?

  def authenticate!
    redirect_to new_user_path and return unless signed_in?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      set_user_session(@user)
      create_user_on_authy(@user)
      send_authy_sms(@user)
      redirect_to show_verify_users_path
    else
      render :new
    end
  end

  def show_verify
    return redirect_to new_user_path unless session[:user_id]
  end

  def verify
    @user = current_user
    token = Authy::API.verify(id: @user.authy_id, token: params[:token])

    if token.ok?
      @user.verify!
      send_message("You did it! Signup complete :)", user: @user)
      redirect_to user_path(@user)
    else
      flash.now[:danger] = "Incorrect code, please try again"
      render :show_verify
    end
  end

  private

  def user_params
    params
      .require(:user)
      .permit(:email, :password, :name, :country_code, :phone_number)
  end

  def create_user_on_authy(user)
    Authy::API.register_user(
      email:        user.email,
      cellphone:    user.phone_number,
      country_code: user.country_code
    ).tap do |authy|
      user.update(authy_id: authy.id)
    end
  end

  def send_authy_sms(user)
    Authy::API.request_sms(id: user.authy_id)
  end

  def send_message(content, user:)
    client = Twilio::REST::Client.new(twilio_config[:account_sid], twilio_config[:auth_token])
    client.api.accounts(twilio_config[:account_sid]).messages.create(
      from: twilio_config[:caller],
      to:   user.formatted_phone_number,
      body: content
    )
  end

  def twilio_config
    @twilio_config ||= Rails.application.credentials.twilio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_slideshow.html.erb
<div data-controller="slideshow">
  <button data-action="slideshow#previous">←</button>
  <button data-action="slideshow#next">→</button>

  <div data-target="slideshow.slide" class="slide">🐵</div>
  <div data-target="slideshow.slide" class="slide">🙈</div>
  <div data-target="slideshow.slide" class="slide">🙉</div>
  <div data-target="slideshow.slide" class="slide">🙊</div>

  <button data-action="slideshow#previous">←</button>
  <button data-action="slideshow#next">→</button>
</div>

app/views/home/index.html.erb
<%= render 'slideshow' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>DialAway</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/top_bar' %>

    <main role="main" class="container">
      <%= yield %>
    </main>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
      </div>
    </footer>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/shared/_top_bar.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Fixed navbar</a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbar-collapse"
      aria-controls="navbar-collapse"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/users/new.html.erb
<h1>Ready to *Dial Away*?</h1>
<p> Thanks for your interest in signing up! Can you tell us a bit about yourself?</p>

<% if @user.errors.any? %>
  <h2>Oops, something went wrong!</h2>

  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end -%>
  </ul>
<% end -%>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name, "Tell us your name:" %>
    <%= f.text_field :name, class: "form-control", placeholder: "Jane Doe", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :email, "Enter Your E-mail Address:" %>
    <%= f.email_field :email, class: "form-control", placeholder: "me@mydomain.com", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :password, "Enter a password:" %>
    <%= f.password_field :password, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :country_code %>
    <%= f.text_field :country_code, class: "form-control", id: "authy-countries", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.phone_field :phone_number, class: "form-control", id: "authy-cellphone", required: true %>
  </div>
  <button class="btn btn-primary">Sign up</button>
<% end -%>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p>Account Status: <% if @user.verified? %>Verified<% else -%>Not Verified<% end -%>
<% if !@user.verified? %>
<p>
  <%= link_to "Verify your account now.", verify_path %>
</p>
<% end -%>

app/views/users/show_verify.html.erb
<h1>Just To Be Safe...</h1>
<p>
    Your account has been created, but we need to make sure you're a human
    in control of the phone number you gave us. Can you please enter the
    verification code we just sent to your phone?
</p>
<%= form_tag verify_user_path(@user) do %>
  <div class="form-group">
    <%= label_tag :code, "Verification Code:" %>
    <%= text_field_tag :token, '', class: "form-control" %>
  </div>
  <button type="submit" class="btn btn-primary">Verify Token</button>
<% end -%>

<hr>
<%= form_tag users_resend_path do %>
  <button type="submit" class="btn">Resend code</button>
<% end -%>